mango/social/__init__.py
# social __init__.py

from flask import Blueprint

from flask_oauthlib.client import OAuth

social = Blueprint('social', __name__, static_folder = 'static', template_folder = 'templates', static_url_path='/social/static')
oauth = OAuth()
from . import views

mango/social/views.py
from flask import session, request, url_for, redirect, render_template, flash, abort
from .models import User, PrivateMessage, UsersRelationship, Notification, NotificationHistory
from flask_login import login_user, login_required, logout_user, current_user
from . .db import db
from . .config import GOOGLE_ID, GOOGLE_SECRET, FACEBOOK_APP_ID, FACEBOOK_APP_SECRET, VK_APP_KEY, VK_APP_SECRET
from datetime import datetime
import json

from . import social, oauth

from . .path import ROOT_DIR, UPLOAD_DIR

from PIL import Image
from . .toolbox import get_hash, how_long_ago

from sqlalchemy.sql import or_, and_

from . .mailer import Mailer

from sqlalchemy import desc

import requests

from . .geo.views import get_tips_data, get_all_tags
from . .geo.models import Tip

from . .logger import Log



def welcome_procedure():
    Notification.add(current_user.id, 'personal', 'Добро пожаловать на КУДАБЫ!!! Как здорово, что вы к нам присоединились! :)')
    Mailer.welcome_mail(current_user.contact_email)


# VK OAUTH
#=============================================================

vk = oauth.remote_app(
    'vk',
    consumer_key=VK_APP_KEY,
    consumer_secret=VK_APP_SECRET,
    request_token_params={'scope': 'email, username'},
    base_url='https://api.vk.com/method/',
    request_token_url=None,
    access_token_url='https://oauth.vk.com/access_token',
    authorize_url='https://oauth.vk.com/authorize'
)

@social.route('/vk-login', methods=['GET'])
def v_login():
    Log.register(action='social.route:v_login')
    if request.args and request.args['follow']:
        session['follow'] = request.args['follow']
    return vk.authorize(callback=url_for('social.v_authorized', _external=True))


@social.route('/vk-login/authorized')
def v_authorized():
    just_registered = False
    resp = vk.authorized_response()
    if resp is None:
        return 'Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )
    ac_token  = resp['access_token']
    session['vk_token'] = (resp['access_token'], '')

    user_info = json.loads(
                    requests.get('https://api.vk.com/method/users.get?user_ids=%s&access_token=%s' % (resp['user_id'], ac_token))
                    .text)
    user_info = user_info['response'][0]

    username = user_info['first_name']+" "+user_info['last_name']
    email = resp['email']
    uid = user_info["uid"]

    user = User.query.filter_by(vk_id=uid).first()
    if user is None:
        user = User.query.filter_by(register_email=email).first()
        if user is None:
            Log.register(action='v_register', data={"marker":session['marker'], "email":email})
            user = User.register_vk_user(username, email, uid)
            user.registered_at = datetime.utcnow()
            just_registered = True
        else:
            user.vk_id = uid
            user.vk_username = username

    user.last_login = datetime.utcnow()
    db.session.add(user)
    db.session.commit()
    login_user(user)
    Log.register(action='user_login', data={"user":{"nickname": user.nickname, "id": user.id}, "method":"vk"})
    if just_registered:
        welcome_procedure()
    if "follow" in session:
        next_url = session["follow"]
    else:
        next_url = url_for('root')
    return redirect(next_url)


@vk.tokengetter
def get_vk_oauth_token():
    return session.get('vk_token')

# GOOGLE OAUTH
#=============================================================
google = oauth.remote_app(
    'google',
    consumer_key=GOOGLE_ID,
    consumer_secret=GOOGLE_SECRET,
    request_token_params={
        'scope': 'email'
    },
    base_url='https://www.googleapis.com/oauth2/v1/',
    request_token_url=None,
    access_token_method='POST',
    access_token_url='https://accounts.google.com/o/oauth2/token',
    authorize_url='https://accounts.google.com/o/oauth2/auth',
)


@social.route('/google-login', methods=['GET'])
def g_login():
    Log.register(action='social.route:g_login')
    if request.args and request.args['follow']:
        session['follow'] = request.args['follow']
    return google.authorize(callback=url_for('social.g_authorized', _external=True))


@social.route('/google-login/authorized')
def g_authorized():
    just_registered = False
    resp = google.authorized_response()
    if resp is None:
        return 'Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )
    session['google_token'] = (resp['access_token'], '')
    me = google.get('userinfo')

    user = User.query.filter_by(google_id=me.data['id']).first()
    if user is None:
        user = User.query.filter_by(register_email=me.data['email']).first()
        if user is None:
            Log.register(action='g_register', data={"marker":session['marker'], "email":me.data['email']})
            user = User.register_google_user(me.data['name'], me.data['email'], me.data['id'])
            just_registered = True
            user.registered_at = datetime.utcnow()
        else:
            user.google_id = me.data['id']
            user.g_username = me.data['name']
    user.last_login = datetime.utcnow()
    db.session.add(user)
    db.session.commit()
    login_user(user)
    Log.register(action='user_login', data={"user":{"nickname": user.nickname, "id": user.id}, "method":"google"})
    if just_registered:
        welcome_procedure()
    if "follow" in session:
        next_url = session["follow"]
    else:
        next_url = url_for('root')
    return redirect(next_url)


@google.tokengetter
def get_google_oauth_token():
    return session.get('google_token')


# FACEBOOK OAUTH
#=============================================================

facebook = oauth.remote_app('facebook',
                            base_url='https://graph.facebook.com/',
                            request_token_url=None,
                            access_token_url='/oauth/access_token',
                            authorize_url='https://www.facebook.com/dialog/oauth',
                            consumer_key=FACEBOOK_APP_ID,
                            consumer_secret=FACEBOOK_APP_SECRET,
                            request_token_params={'scope': ['email', 'public_profile']}
                            )


@social.route('/facebook-login', methods=['GET'])
def f_login():
    Log.register(action='social.route:f_login')
    if request.args and request.args['follow']:
        session['follow'] = request.args['follow']
    return facebook.authorize(callback=url_for('social.f_authorized', _external=True))


@social.route('/facebook-login/authorized')
def f_authorized():
    just_registered = False
    resp = facebook.authorized_response()
    if resp is None:
        return 'Access denied: reason=%s error=%s' % (
            request.args['error_reason'],
            request.args['error_description']
        )
    session['facebook_token'] = (resp['access_token'], '')
    me = facebook.get('/me?fields=name,email,picture')

    user = User.query.filter_by(facebook_id=me.data['id']).first()
    if user is None:
        user = User.query.filter_by(register_email=me.data['email']).first()
        if user is None:
            Log.register(action='f_register', data={"marker":session['marker'], "email":me.data['email']})
            user = User.register_facebook_user(me.data['name'], me.data['email'], me.data['id'])
            just_registered = True
            user.registered_at = datetime.utcnow()
        else:
            user.facebook_id = me.data['id']
            user.f_username = me.data['name']
    user.last_login = datetime.utcnow()
    db.session.add(user)
    db.session.commit()
    login_user(user)
    Log.register(action='user_login', data={"user":{"nickname": user.nickname, "id": user.id}, "method":"facebook"})
    if just_registered:
        welcome_procedure()
    if "follow" in session:
        next_url = session["follow"]
    else:
        next_url = url_for('root')
    return redirect(next_url)


@facebook.tokengetter
def get_facebook_oauth_token():
    return session.get('facebook_token')


# LOGIN LOGOUT
#=============================================================

@social.route('/login')
def login():
    return redirect(url_for('root'))


@social.route('/logout')
@login_required
def logout():
    Log.register(action='user_logout', data={"user":{"nickname": current_user.nickname, "id": current_user.id}, "marker":session['marker']})
    session.pop('google_token', None)
    session.pop('facebook_token', None)
    logout_user()
    return redirect(url_for('root'))




# USER PROFILE
#=============================================================
@social.route('/profile')
@login_required
def profile():
    Log.register(action='social.route:profile')
    u = current_user
    return render_template('profile.html', u=u)


@social.route('/check-nick', methods=['POST'])
@login_required
def check_nick():
    Log.register(action='social.post:check_nick', data=request.json)
    query = request.json
    res = User.query.filter_by(nickname=query['val']).count()
    return json.dumps({"val": res})


@social.route('/save-nick', methods=['POST'])
@login_required
def save_nick():
    Log.register(action='social.post:save_nick', data=request.json)
    query = request.json
    if User.query.filter_by(nickname=query['val']).count() == 0:
        current_user.nickname = query['val']
        db.session.add(current_user)
        db.session.commit()
        return json.dumps({"val": True})
    return json.dumps({"val": False})


@social.route('/save-info', methods=['POST'])
@login_required
def save_info():
    query = request.json
    try:
        if query['type'] == 'url':
            Log.register(action='social.post:save_url', data=request.json)
            url = query['val']
            current_user.url = url if url.startswith('http:') or url.startswith('https:') else 'http://'+url

mango/social/templates/favorites.html
{% from 'macros.html' import inline_menu %}

{% extends "base.html" %}

{% block title %}Избранное{% endblock %}

{% block styles %}
{{ super() }}
    {% assets "favorites_css" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
{% endblock %}

{% block page_content %}
<div class="container">

    {{inline_menu('favorites')}}

    <div class="row" id ="profile__main">
      <div class="col-lg-6 col-lg-offset-3">

        <div id="tipsflow"></div>


      </div> <!-- col -->
    </div> <!-- row -->



</div> <!-- container -->

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
      var jsonData = {{json_data|tojson|safe}};
      var signedIn = "{{signed_in}}";
    </script>
    {% assets "favorites_js" %}
        <script src ="{{ ASSET_URL }}" type="text/javascript"></script>
    {% endassets %}

{% endblock %}

mango/social/templates/macros.html
{% macro inline_menu(page) %}
    <div class="row" id="profile__menu">
        <div class="col-lg-12">
            <a class="inline-menu__item 
                {% if page=='my_tips' %}
                inline-menu__item--selected
                {% endif %}" href="{{url_for('social.my_tips')}}">Мои советы</a>
            <a class="inline-menu__item 
                {% if page=='favorites' %}
                inline-menu__item--selected
                {% endif %}" href="{{url_for('social.favorites')}}">Избранное</a>
            <a class="inline-menu__item
                {% if page=='events' %}
                inline-menu__item--selected
                {% endif %}" href="{{url_for('social.user_events')}}">События <span class="badge serverNotsCount"></span></a>
            <a class="inline-menu__item 
                {% if page=='profile' %}
                inline-menu__item--selected
                {% endif %}" href="{{url_for('social.profile')}}">Профиль</a>
            <a class="
                inline-menu__item 
                {% if page=='messenger' %}
                inline-menu__item--selected
                {% endif %}" 
            href="{{url_for('social.messenger')}}">Личные сообщения <span class="serverMsgIndicator"><span class="badge serverMsgCount"></span></span></a>
        </div>
    </div>
{% endmacro %}

mango/social/templates/messenger.html
{% from 'macros.html' import inline_menu %}

{% extends "base.html" %}

{% block title %}Ваш профиль: {{u.nickname}}{% endblock %}

{% block metas %}
{{super()}}
<meta name="uid" content="{{ u.id }}">
<meta name="seluid" content="{{ sel }}">
{% endblock %}

{% block styles %}
{{ super() }}
<!--     <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/ui.css') }}">
    <link rel=stylesheet type=text/css href="{{ url_for('social.static', filename='css/messenger.css') }}"> -->
        {% assets "messenger_css" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
{% endblock %}

{% block page_content %}
<div class="container">
    
    {{inline_menu('messenger')}}

    <div class="row" id="profile_messenger">
        <h2 class="row__header">Личные сообщения</h2>
        <div class="col-lg-12">
            
                <div class="row" id="messenger">
                    <div class="col-lg-4">
                        <section>
                            <div class="section-body">
                            <h3 class="col__header">Пользователи</h3>

                            <ul id="v__contact-list">
        
                                    <li class="v__contact-list__item" 
                                    v-for="c in contactList"
                                    v-on:click="selectContact($index)"
                                    v-bind:class="{'v__contact-list__item--selected': selectedUserIndex==$index}">
                                        <img v-bind:src="c.img" class="img img-responsive contact-avatar" />
                                        <span v-text="c.name"></span>
                                        <span v-if="c.unread" 
                                            v-text="c.unread"
                                            class="badge">
                                        </span>
                                    </li>
        
                            </ul>
                            </div>
                        </section>
                    </div>
                    <div class="col-lg-8">
                        <section>
                            <div class="section-body">
                                <div>
                                    <div id="v__chat-header">
                                        <div id="v__chat-header__title">
                                            <h3 class="col__header" id="v__chat-header__title-text" v-text="headerText">
                                            </h3>
                                        </div>
                                        <div id="v__chat-header__controls"
                                                v-show="selectedUserIndex!= -1">
                                            <button class="btn"
                                                    @click="toggleBanUser"
                                                    v-bind:class="{'ban-enabled':userIsBanned,'ban-disabled': !userIsBanned}" 
                                                    id="v__chat-header__ban-button"
                                                    :title="banButtonTitle">
                                                <i class="glyphicon glyphicon-ban-circle"></i>
                                            </button>
                                        </div>
                                        <div class="clearfix"></div>
                                        <div id="v__chat-header__status" class="alert alert-warning">
                                        </div>
                                    </div>
                                </div>
                                <div class="divider"></div>
                                <div id="v__chat">
                                    <div id="v__chat__placeholder" v-if="messages.length==0">
                                            <span v-show="contactList.length">Выберите пользователя для просмотра переписки</span>
                                            <span v-show="!contactList.length">Чтобы начать переписку отправьте сообщение со страницы профиля нужного пользователя</span>
                                    </div>
                                    <div v-if="onlyLastMessages">
                                        Показаны последние 10 сообщений.
                                        <span class="plink" @click="openAllMessages">Показать всю переписку</span>
                                    </div>
                                    <div class="msg" 
                                        v-bind:class="{'msg__to-me':selectedUser.uid==msg.sender, 'msg__from-me':selectedUser.uid !=msg.sender, }"
                                        v-for="msg in messages" 
                                        >
                                        <div class="msg__prefix" v-text="msg.ago"></div>
                                         <div class="msg__bubble" v-text="msg.text"></div>

                                    </div>
                                </div>
                                <div class="divider"></div>
                                <textarea id="msg__textarea" v-model="messageArea" placeholder="Ваше сообщение"></textarea>
                                <button id="msg__send-button" 
                                        class="btn btn-large btn-default" 
                                        v-bind:disabled="sendButtonDisabled || selectedUser.isBanned"
                                        @click="sendMessage">
                                    Отправить
                                </button>
                            </div>
                        </section>

                    </div>

                </div>
            
        </div>
    </div>


    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class="flashes">
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}



</div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    {% assets "messenger_js" %}
        <script src ="{{ ASSET_URL }}" type="text/javascript"></script>
    {% endassets %}
{% endblock %}

mango/social/templates/my_tips.html
{% from 'macros.html' import inline_menu %}

{% extends "base.html" %}

{% block title %}Избранное{% endblock %}

{% block styles %}
{{ super() }}
    {% assets "my_tips_css" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
{% endblock %}

{% block page_content %}
<div class="container">

    {{inline_menu('my_tips')}}

    <div class="row" id ="profile__main">
      <div class="col-lg-6 col-lg-offset-3">

        <div id="tipsflow"></div>


      </div> <!-- col -->
    </div> <!-- row -->



</div> <!-- container -->

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
      var jsonData = {{json_data|tojson|safe}};
      var signedIn = "{{signed_in}}";
    </script>
    {% assets "my_tips_js" %}
        <script src ="{{ ASSET_URL }}" type="text/javascript"></script>
    {% endassets %}
{% endblock %}

mango/social/templates/profile.html
{% from 'macros.html' import inline_menu %}

{% extends "base.html" %}

{% block title %}Ваш профиль: {{u.nickname}}{% endblock %}

{% block styles %}
{{ super() }}
    {% assets "profile_css" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
{% endblock %}

{% block page_content %}
<div class="container">

    {{inline_menu('profile')}}

    <div class="row" id ="profile__main">
        <h2 class="row__header">Профиль пользователя</h2>
        <div class="col-lg-3">

        <section id="avatar__dropzone" class="dropzone">
          <div class="section-body">
                    <img class="avatar-big" id="avatar__image" src="{{u.get_avatar()}}"/>
          <div id="dnd-cta">Перетащите новое фото сюда</div>
          <div id="or">-или-</div>
          <div class="browser">
            <label>
              <span>Выберите файл</span>
              <input type="file" name="files[]" multiple="multiple" title='Click to add Files'>
            </label>
          </div>
          </div>
        </section>


        </div>

        <div class="col-lg-9">
            <section id="userinfo">
              <div class="section-body">
                <h1 id="nickname__title">{{u.nickname}}</h1>
                <a href="{{url_for('social.public_profile', uid=u.id)}}">Посмотреть публичный профиль</a>
                <div class="divider"></div>

                <label class="form-label" for="nickname__edit-input">Никнейм:</label>
                <div class="form-inline">
                  <div id ="nickname__group" class="form-group" >
                    {% if u.nickname %}{% set nick=u.nickname %}{% endif %}
                    <input type="text" class="form-control" id="nickname__edit-input" value="{{nick}}" placeholder="Add nickname">
                  </div>
                  <button id="nickname__save-button" class="btn btn-default">Сохранить</button>
                </div>
                <div id="nickname__status"></div>

                <label class="form-label" for="nickname__edit-input">E-mail для связи:</label>
                <div class="form-inline">
                  <div id ="email__group" class="form-group" >
                    {% set es=u.get_email_status() %}
                    <input type="text" class="form-control"  id="email__edit-input" value="{{es['email']}}" placeholder="Имя пользователя"
                      >
                  </div>
                  <button id="email__save-button" class="btn btn-default">Сохранить</button>
                </div>
                <div id="email__status"></div>

                <label class="form-label" for="website__edit-input">Адрес сайта:</label>
                <div class="form-inline">
                  <div id ="website__group" class="form-group" >
                    <input type="text" class="form-control"  id="website__edit-input" value="{% if u.url %}{{u.url}}{% endif %}" placeholder="http://..."
                      >
                  </div>
                  <button id="website__save-button" class="btn btn-default">Сохранить</button>
                </div>
                <div id="website__status"></div>


                <label class="form-label" for="selfinfo__edit-input">Статус</label>
                <div class="form-inline">
                  <div id ="selfinfo__group" class="form-group" >
                    <textarea class="form-control"  id="selfinfo__edit-input" value="" placeholder="О себе..."
                      >{% if u.status %}{{u.status}}{% endif %}</textarea>
                  </div>
                  <br />
                  <button id="selfinfo__save-button" class="btn btn-default">Сохранить</button>
                </div>
                <div id="selfinfo__status"></div>

               </div> 
            </section>
            <section>
              <div class="section-body">
                <h2>Авторизация</h2>
                {% if u.google_id %}
                    <div><span class="glyphicon glyphicon-ok-sign" style="color:green"> </span> Вы вошли с помощью Google</div>
                {% endif %}
                {% if u.facebook_id %}
                    <div><span class="glyphicon glyphicon-ok-sign" style="color:green"> </span> Вы вошли с помощью Facebook</div>
                {% endif %}
                {% if u.vk_id %}
                    <div><span class="glyphicon glyphicon-ok-sign" style="color:green"> </span> Вы вошли с помощью ВКонтакте</div>
                {% endif %}
                <div class="divider"></div>
                <a class="btn btn-large btn-warning" href="{{url_for('social.logout')}}"><i class="fa fa-sign-out" title="Выйти"></i>&nbsp;Выйти</a>
              </div>
            </section>
        </div>

    </div>


    {% with messages = get_flashed_messages() %}
      {% if messages %}
        <ul class="flashes">
        {% for message in messages %}
          <li>{{ message }}</li>
        {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}



</div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    {% assets "profile_js" %}
        <script src ="{{ ASSET_URL }}" type="text/javascript"></script>
    {% endassets %}
{% endblock %}

mango/social/templates/public_profile.html
{% extends "base.html" %}

{% block title %}Профиль пользователя {{u.nickname}}{% endblock %}

{% block styles %}
{{ super() }}
    {% assets "public_profile_css" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}" />
    {% endassets %}
{% endblock %}

{% block page_content %}
<div class="container">


    <div class="row" id ="profile__main">
<!--         <div class="col-lg-3">

        <section id="avatar">
              
        </section>


        </div> -->

        <div class="col-lg-8 col-lg-offset-2" style="text-align:center">
            <section id="userinfo">
              <div class="section-body">
              <img class="avatar-big" id="avatar__image" src="{{u.get_avatar()}}"/>
                <h1 id="nickname__title">{{u.nickname}}</h1>
                {% if u.status %}<p>{{u.status}}</p>{% endif %}
                {% if u.url %}<p><a href="{{u.url}}" target="_blank">{{u.url}}</a></p>{% endif %}

                <div class="divider"></div>

      
                {% set stats=u.get_stats() %}
                Посетил(а) {{stats.places_text}}
                <br/>
                {% for p in stats.places %}
                  {% if loop.index>1 %} &#8226;{% endif %}
                  <a href="{{url_for('geo.places', us=p.url_string)}}">{{p.name}}</a>
                {% endfor %}
                <br>

                Посетил(а) {{stats.countries_text}}
                <br/>
                {% for c in stats.countries %}
                  {% if loop.index>1 %} &#8226;{% endif %}
                  <a href="{{url_for('geo.country', us=c.url_string)}}">{{c.name}}</a>
                {% endfor %}


                {% if current_user.id!= u.id %}
                <div id="user-actions__panel">

                  <button id="subscribe__btn" class="btn btn-large btn-default" v-if="!subscribed" @click="subscribe">
                    <i class="fa fa-plus"></i>
                    &nbsp;Подписаться
                  </button>

                  <button id="subscribe__btn" class="btn btn-large btn-default" v-if="subscribed" @click="unsubscribe">
                    <i class="fa fa-minus"></i>
                    &nbsp;Отписаться
                  </button>

                  <button id="private-message__show" class="btn btn-large btn-default" @click="showMessageForm">
                    <i class="glyphicon glyphicon-envelope" title="Выйти"></i>
                    &nbsp;Личное сообщение
                  </button>
                  <div id="private-message__form" v-show="showingMessageForm">
                    <div class="divider"></div>
                    <h4>Личное сообщение пользователю {{u.nickname}}</h4>
                    <textarea id="private-message__textarea" v-model="messageText"></textarea>
                    <button id="private-message__send-button" class="btn btn-large btn-default" @click="sendPrivateMessage">
                      Отправить
                    </button>
                  </div>

                  <div id="user-actions__status" class="alert alert-success" v-show="messageSuccess">
                    Ваше сообщение успешно отправлено!<br/>
                    Всю переписку вы можете посмотреть в вашем профиле, в разделе 
                    <a href="{{url_for('social.messenger')}}"> "Личные сообщения"</a>
                  </div>

                </div>
                {% endif %}
                </div>

            </section>
            <section>
              <div id="tipsflow" class="section-body"></div>
            </section>          
            
        </div>
      </div>



{% include 'login_modal.html'%}

</div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script type="text/javascript">
      var userId = {{u.id}};
      var canSendPm = "{{can_send_pm}}";
      var subscribed = "{{subscribed}}";
      var signedIn = {{signed_in|lower}};
      var jsonData = {{json_data|tojson|safe}};
    </script>
    {% assets "public_profile_js" %}
        <script src ="{{ ASSET_URL }}" type="text/javascript"></script>
    {% endassets %}
{% endblock %}

mango/social/templates/subscriptions.html
{% from 'macros.html' import inline_menu %}

{% extends "base.html" %}

{% block title %}Избранное{% endblock %}

{% block styles %}
{{ super() }}
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='css/ui.css') }}">
{% endblock %}

{% block page_content %}
<div class="container">

    {{inline_menu('subscriptions')}}

    <div class="row" id ="profile__main">
      <div class="col-lg-6 col-lg-offset-3">

        RESERVED


      </div> <!-- col -->
    </div> <!-- row -->



</div> <!-- container -->

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src ="{{ url_for('static', filename="js/common.js") }}" type="text/javascript"></script>
    <script src ="{{ url_for('social.static', filename="js/subscriptions.js") }}" type="text/javascript"></script>
{% endblock %}